# Introduction

In [3]:
#import library

import numpy as np

In [4]:
arr= np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
arr[1][2]

7

In [18]:
name = np.array([1,2,'3','hello'])
name
for hi in name:
    print("YES")

YES
YES
YES
YES


In [5]:
#dimension of the array

print(arr.ndim) # ndim is the keyword to access the dimension of the array
print(arr.shape) #shape is to get the size of the matrix
print(arr.data) #to know the location where the array is saved in memory locations
print(arr.size) #to get the number of elements in array
print(type(arr))#to get the type of array

2
(2, 4)
8
<class 'numpy.ndarray'>


# lab 1 Random Number Generator Using Numpy

In [6]:
from numpy import random #from numpy library we are importing random module

x= random.randint(10,size=(13,10))
x

array([[4, 7, 5, 4, 8, 1, 5, 9, 9, 3],
       [2, 3, 3, 6, 3, 8, 8, 1, 9, 8],
       [4, 9, 5, 5, 8, 6, 0, 3, 2, 4],
       [4, 7, 0, 8, 9, 8, 0, 5, 5, 2],
       [4, 8, 3, 5, 7, 2, 1, 5, 0, 5],
       [6, 7, 9, 5, 8, 8, 1, 6, 7, 4],
       [6, 5, 9, 4, 9, 7, 5, 6, 6, 1],
       [3, 6, 5, 8, 3, 9, 3, 5, 6, 1],
       [0, 7, 2, 4, 1, 3, 4, 2, 8, 5],
       [4, 6, 2, 3, 1, 2, 7, 7, 3, 6],
       [3, 3, 6, 4, 0, 3, 6, 7, 3, 1],
       [2, 5, 1, 3, 5, 6, 3, 6, 2, 4],
       [2, 0, 5, 1, 1, 8, 1, 5, 4, 3]])

In [56]:
# dice game

import numpy as np
from numpy import random

dice1 = random.randint(6)
if dice1==0:
        dice1 = random.randint(6)

dice2 = random.randint(6)
if dice2==0:
        dice2 = random.randint(6)
print("dice1:",dice1,'\n'"dice2:",dice2)



dice1: 1 
dice2: 1


In [67]:

import numpy as np
from numpy import random

dice1 = random.randint(6)
for dice1  0:
    dice1

SyntaxError: invalid syntax (<ipython-input-67-b4dabfe0c327>, line 5)

In [7]:
y= random.rand(10)
y

array([0.52359433, 0.3802663 , 0.48105411, 0.9427539 , 0.20180464,
       0.3513595 , 0.32571025, 0.85843831, 0.71939154, 0.6700673 ])

In [34]:
x= random.randint(10,size=(2,2))
random.seed(0) #always give some value in the brackets then only u will get the same number
x

array([[5, 0],
       [3, 3]])

# Numpy operations

In [8]:
import numpy
from numpy import random

z= random.random((3,2))
z

array([[0.35822658, 0.46082087],
       [0.97521568, 0.19280298],
       [0.79155837, 0.93096335]])

In [9]:
#creating a zero matrix/arrays 

zero= np.zeros((3,3)) #zeros is the function to get zero matrix
zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
#identity matrix

idt = np.eye(3) #eye is the function to get identity matrix
idt

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
#ones matrix

one= np.ones((3,3)) # ones is the function to get one's matrix
one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
#create a constant matrix

const=np.full((3,3),5) #full is the function to get matrix of any number
const

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

# Array indexing and slicing

In [69]:
arr = np.array([[2,3,3,4,],[5,6,7,8],[8,7,6,5],[9,10,11,12]])
arr

array([[ 2,  3,  3,  4],
       [ 5,  6,  7,  8],
       [ 8,  7,  6,  5],
       [ 9, 10, 11, 12]])

In [36]:
arr[0]

array([2, 3, 3, 4])

In [45]:
arr[2][2]

6

In [46]:
arr[2][2]=13
arr

array([[ 2,  3,  3,  4],
       [ 5,  6,  7,  8],
       [ 8,  7, 13,  5],
       [ 9, 10, 11, 12]])

In [60]:
nevil = np.array([[2,3,3,4],[5,6,7,8],[8,7,6,5],[9,10,11,12]])
nevil

array([[ 2,  3,  3,  4],
       [ 5,  6,  7,  8],
       [ 8,  7,  6,  5],
       [ 9, 10, 11, 12]])

In [55]:
#slicing

arr[1: ,1:1] 

array([], shape=(3, 0), dtype=int32)

In [56]:
#arr[slicing of rows,slicing of columns]
#arr[start:end,start:end]

arr[1:2,2:3]

array([[7]])

# Array broadcasting 

In [57]:
#addition od matrix
x= arr+arr
print(x)

[[ 4  6  6  8]
 [10 12 14 16]
 [16 14 26 10]
 [18 20 22 24]]


In [58]:
print(np.add(arr,arr))

[[ 4  6  6  8]
 [10 12 14 16]
 [16 14 26 10]
 [18 20 22 24]]


In [63]:
print(np.subtract(arr,arr))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [62]:
y =arr-arr
print(y)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [73]:
print(np.multiply(arr,arr))

[[  4   9   9  16]
 [ 25  36  49  64]
 [ 64  49 169  25]
 [ 81 100 121 144]]


In [75]:
print(np.divide(arr,arr), type=int)

TypeError: 'type' is an invalid keyword argument for print()

In [74]:
#to find the square root
np.sqrt(arr)

array([[1.41421356, 1.73205081, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [2.82842712, 2.64575131, 3.60555128, 2.23606798],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

In [76]:
np.sum(arr)

113

In [83]:
np.sum(const,axis=0)

array([15, 15, 15])

In [82]:
np.sum(const,axis=1)

array([15, 15, 15])

In [84]:
np.sum(const[1],axis=0)

15

# Calculate the BMI of the players

In [90]:
#height of players in inches
_
height_in=[79,76,60,67,67,66,65,]  #you can keep any variable name not necessary it should have _np
ht_np = np.array(height_in)
#convert inch to meters
ht_np= ht_np*0.0245
ht_np

array([1.9355, 1.862 , 1.47  , 1.6415, 1.6415, 1.617 , 1.5925])

In [151]:
height_in=[random.randint(10)]
height_in

[6]

In [154]:
#weight of the players in pounds

#weight_pd = random.randint(60:90,10) # i am trying to get a specified random numbers ranging from 60-90

num = random.randint(90)
if num(40,23):
    print("hi")
else:
    print("bye")


TypeError: 'int' object is not callable

In [96]:
weight_in=[79,76,60,67,67,66,65,]
wt_np = np.array(weight_in)
#convert to kg
wt_np= wt_np*0.45
wt_np

array([35.55, 34.2 , 27.  , 30.15, 30.15, 29.7 , 29.25])

In [98]:
#calculate bmi of players

bmi_np=wt_np/ht_np**2
bmi_np

array([ 9.48971684,  9.86431092, 12.49479384, 11.18936761, 11.18936761,
       11.35890349, 11.53365585])

In [101]:
bmi_np[bmi_np<20]

array([ 9.48971684,  9.86431092, 12.49479384, 11.18936761, 11.18936761,
       11.35890349, 11.53365585])

In [102]:
players = np.array([wt_np,ht_np])

In [103]:
players

array([[35.55  , 34.2   , 27.    , 30.15  , 30.15  , 29.7   , 29.25  ],
       [ 1.9355,  1.862 ,  1.47  ,  1.6415,  1.6415,  1.617 ,  1.5925]])

In [104]:
players.shape

(2, 7)

In [105]:
#to transpose a matrix 

p_T = players.T
p_T

array([[35.55  ,  1.9355],
       [34.2   ,  1.862 ],
       [27.    ,  1.47  ],
       [30.15  ,  1.6415],
       [30.15  ,  1.6415],
       [29.7   ,  1.617 ],
       [29.25  ,  1.5925]])

In [106]:
p_T.shape

(7, 2)

# Statistical Operation

In [107]:
# min , max ,mean , median ,std ,var,corrcoef ,perc

In [122]:
print(np.amax(ht_np))
print(np.amax(wt_np))
print(np.amin(ht_np))
print(np.amin(wt_np))
print(np.median(wt_np))
print(np.median(ht_np))
print(np.std(wt_np))
print(np.var(wt_np))
print(np.corrcoef(wt_np,ht_np)) # co-relation between two co-efficient 


1.9355
35.550000000000004
1.47
27.0
30.150000000000002
1.6415
2.751548729018491
7.571020408163273
[[1. 1.]
 [1. 1.]]


In [123]:
#Boolean 

a=[False,True,False,True,False,True ]
a

[False, True, False, True, False, True]

In [126]:
b=np.array(a)

In [127]:
b.sum() # since we cannot perfrom array functions on list we are defining a variable b

3

In [128]:
b.any()

True

In [130]:
b.all()

False

In [137]:

a=['b','b','r','s','c' ]
a

['b', 'b', 'r', 's', 'c']

In [138]:
np.unique(a)

array(['b', 'c', 'r', 's'], dtype='<U1')

In [139]:
a=['b','b','r','w','q' ]
z=np.array(a)
z

array(['b', 'b', 'r', 'w', 'q'], dtype='<U1')

In [140]:
np.unique(z)

array(['b', 'q', 'r', 'w'], dtype='<U1')